name: json_dart_generator
description:
  Convert json data to dart class,
  Support multiple formats(root is array / multiple array etc).
version: 1.0.1+1
homepage: https://github.com/MagicalWater/json_dart_generator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_style: "^2.0.0"
  args: "^2.1.0"
  collection: "^1.15.0"

executables:
  json_dart_generator: